{{ if .Values.transcoder.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Chart.Name }}-{{ .Values.transcoder.triggerAuthorization.name }}-ta
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    env: {{ .Values.environment }}
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: {{ .Chart.Name }}-{{ .Values.transcoder.triggerAuthorization.secretTarget }}-sk
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: {{ .Chart.Name }}-{{ .Values.transcoder.triggerAuthorization.secretTarget }}-sk
      key: AWS_SECRET_ACCESS_KEY
{{ end }}