{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}-httproute
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    env: {{ .Values.environment }}
spec:
  parentRefs:
  {{ range .Values.httpRoute.parentRefs }}
  - name: {{ .name }}
  {{- end }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
  {{ range .Values.httpRoute.hostnames }}
  - {{ . }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.httpRoute.rules }}
    - matches:
      {{- range .matches }}
        - path:
            type: {{ .path.type }}
            value: {{ .path.value }}
      {{- end }}
      backendRefs:
      {{ range .backendRefs }}
      - name: {{ $.Chart.Name }}-{{ .name }}-svc
        port: {{ .port | int }}
      {{- end }}
  {{- end }}
{{- end }}
