{{- if $.Values.syncSecret }}
{{- range $secretName, $secretData := .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-{{ $secretName }}-sk
  namespace: {{ $.Values.namespace | default $.Release.Namespace | quote }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    env: {{ $.Values.environment | quote }}
    {{- if $secretData.labels }}
    {{- range $labelKey, $labelValue := $secretData.labels }}
    {{ $labelKey }}: {{ $labelValue | quote }}
    {{- end }}
    {{- end }}
type: Opaque
data:
{{- range $key, $value := $secretData.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- end }}
