kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.backend.name }}-cm"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    env: {{ .Values.environment }}
data:
  SERVICE_ENV: {{ .Values.environment }}
