{{ if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name }}-{{ .Values.backend.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    env: {{ .Values.environment }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.backend.name }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.backend.name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.backend.name }}
        image: {{ .Values.repository }}/{{ .Chart.Name }}/{{ .Values.backend.name }}
        imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort | int }}
        envFrom:
        {{- range .Values.backend.configMapRef }}
        - configMapRef:
            name: {{ $.Chart.Name }}-{{ . }}-cm
        {{- end }}
        {{- range .Values.backend.secretRef }}
        - secretRef:
            name: {{ $.Chart.Name }}-{{ . }}-sk
        {{- end }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port | int }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port | int }}
        resources:     
{{ toYaml .Values.resources | indent 10 }}
{{ end }}